#!/usr/bin/env bash

$(brew --prefix)/opt/fzf/install

pushd ~/Repositories/dotfiles
git remote set-url origin git@github.com:kevinlacotaco/dotfiles.git

git submodule init
git submodule update
popd

# Install the latest LTS Node
nvm install --lts
nvm alias default "lts/*"

# Install yarn for projects
npm install -g yarn
